(part "ADS112C04IPW"
    (packageRef "SOP65P640X120-16N")
    (interface
        (port "1" (symbPinId 1) (portName "A0") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%RESET%") (portType INOUT))
        (port "4" (symbPinId 4) (portName "DGND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "AVSS") (portType INOUT))
        (port "6" (symbPinId 6) (portName "AIN3") (portType INOUT))
        (port "7" (symbPinId 7) (portName "AIN2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "REFN") (portType INOUT))
        (port "9" (symbPinId 9) (portName "REFP") (portType INOUT))
        (port "10" (symbPinId 10) (portName "AIN1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "AIN0") (portType INOUT))
        (port "12" (symbPinId 12) (portName "AVDD") (portType INOUT))
        (port "13" (symbPinId 13) (portName "DVDD") (portType INOUT))
        (port "14" (symbPinId 14) (portName "%DRDY%") (portType INOUT))
        (port "15" (symbPinId 15) (portName "SDA") (portType INOUT))
        (port "16" (symbPinId 16) (portName "SCL") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-ADS112C04IPW")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/ADS112C04IPW?qs=55YtniHzbhAHI%252BSH3qtesg%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "ADS112C04IPW")
    (property "Description" "Analog to Digital Converters - ADC 16-Bit 2kSPS 4-Ch Low-Power Delta-Sigma ADC With PGA, Voltage Reference, IDACs, and I2C Interface 16-TSSOP -40 to 125")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/DKDS41/DSANUWW0029291.pdf")
    (property "symbolName1" "ADS112C04IPW")
)
